import { createHmac, timingSafeEqual } from "crypto";
import type { Recipe } from "../data/recipes";

const api="https://api.resend.com";
export function emailHeaders(){return {Authorization:`Bearer ${process.env.RESEND_API_KEY||""}`,"Content-Type":"application/json"};}
export function unsubscribeToken(email:string){return createHmac("sha256",process.env.UNSUBSCRIBE_SECRET||"missing-secret").update(email.toLowerCase()).digest("hex");}
export function validToken(email:string,token:string){const expected=unsubscribeToken(email);try{return token.length===expected.length&&timingSafeEqual(Buffer.from(token),Buffer.from(expected));}catch{return false;}}
export function unsubscribeUrl(email:string){const site=(process.env.SITE_URL||"").replace(/\/$/,"");return `${site}/api/unsubscribe?email=${encodeURIComponent(email)}&token=${unsubscribeToken(email)}`;}
export async function resend(path:string,init:RequestInit={}){const headers=new Headers(init.headers);for(const [key,value] of Object.entries(emailHeaders()))headers.set(key,value);return fetch(`${api}${path}`,{...init,headers,cache:"no-store"});}
export function dailyRecipesHtml(recipes:Recipe[],email:string){const cards=recipes.map(r=>`<div style="border:1px solid #e3d4bb;border-radius:10px;overflow:hidden;margin:20px 0;background:#fff"><img src="${r.image}" alt="${r.title}" style="width:100%;height:210px;object-fit:cover"><div style="padding:22px"><p style="color:#a44220;font-size:11px;font-weight:bold;letter-spacing:1px;text-transform:uppercase">${r.flag} ${r.cuisine} · ${r.time}</p><h2 style="font-family:Georgia,serif;color:#29231b;margin:8px 0">${r.title}</h2><p style="color:#6f665a;line-height:1.6">${r.description}</p><a href="${(process.env.SITE_URL||"").replace(/\/$/,"")}/recipes/${r.slug}" style="display:inline-block;background:#a44220;color:white;text-decoration:none;padding:12px 17px;border-radius:4px;font-weight:bold">Cook this recipe →</a></div></div>`).join("");
 return `<!doctype html><html><body style="margin:0;background:#f7eedc;font-family:Arial,sans-serif"><div style="max-width:650px;margin:auto;padding:35px 18px"><p style="color:#a44220;font-weight:bold;letter-spacing:2px;text-transform:uppercase;font-size:11px">The Copper Spoon</p><h1 style="font-family:Georgia,serif;color:#29231b;font-size:38px">Three delicious ideas for today</h1><p style="color:#6f665a;line-height:1.7">A fresh journey around the world, selected for your kitchen.</p>${cards}<p style="text-align:center;color:#807568;font-size:12px;margin-top:35px">You subscribed to three daily recipes from The Copper Spoon.<br><a href="${unsubscribeUrl(email)}" style="color:#a44220">Unsubscribe from daily emails</a></p></div></body></html>`;
}
